# Generated by Django 4.2.13 on 2024-05-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.IntegerField(default=0),
        ),
    ]
